---
title           : "Measuring psychological ownership and identity in a Finnish blood donor context"
shorttitle      : "Donation ownership"
date            : "`r Sys.setlocale('LC_TIME', 'C'); format(Sys.time())`"

author: 
  - name        : Abigail Edwards
    affiliation : 1
  - name        : Mikko Arvas
    affiliation : 2
  - name        : Lauri Hietajärvi
    affiliation : 3    
  - name        : Johanna Castrén
    affiliation : 2
  - name        : Barbara Masser
    affiliation : 2
    

affiliation:
  - id          : 1
    institution : The University of Queensland, Australia 
  - id          : 2
    institution : Finnish Red Cross Blood Service, Finland
  - id          : 3
    institution : University of Helsinki, Finland
    
header-includes:
  - \usepackage{pdfpages}
  
csl             : manuscript/vox-sanguinis.csl
bibliography      : ["manuscript/references.bib", "manuscript/r-references.bib"]


output: prereg::prereg_pdf
---

<!-- to be submitted to https://prereg-psych.org/ >

# Study Information

## Title
<!-- Provide the working title of your study. It may be the same title that you submit for publication of your final manuscript, but it is not a requirement. The title should be a specific and informative description of a project. Vague titles such as 'Fruit fly preregistration plan' are not appropriate.

Example: Effect of sugar on brownie tastiness. -->

`r rmarkdown::metadata$title`


## Description
<!-- Please give a brief description of your study, including some background, the purpose of the of the study, or broad research questions. The description should be no longer than the length of an abstract. It can give some context for the proposed study, but great detail is not needed here for your preregistration.

Example: Though there is strong evidence to suggest that sugar affects taste preferences, the effect has never been demonstrated in brownies. Therefore, we will measure taste preference for four different levels of sugar concentration in a standard brownie recipe to determine if the effect exists in this pastry. -->

Having a donor self-identity is considered a key motivational factor for sustained blood donation behavior [@calleroRoleidentitySalience1985,@fergusonTypologyBloodDonor2020]. Within Identity Theory, when a new donor first gives blood they develop a role-identity (I am a blood donor). As a novice donor continues to donate, this role-identity is validated, and thus blood donation becomes part of a donor’s self-identity (Being a blood donor is an important part of who I am; [@grubeRoleIdentityOrganizational2000,@masserPredictingBloodDonation2009]. However, despite the link between donor self-identity and donor retention, there are currently no interventions which can foster a sense of identity in donors that do not rely exclusively on repeat donation behavior. 
Psychological ownership (this is mine) is the sense of ownership experienced over both material (e.g., blood collection agency) and abstract immaterial (e.g., blood donation behavior) possessions [@pierceTheoryPsychologicalOwnership2001]. The ownership volunteers experience over a non-profit organisation has been linked to sustained volunteering behavior [@ainsworthFeelingsOwnershipVolunteering2020]. Further, psychological ownership is theoretically associated with identity as it has been proposed that through possession identity is established and maintained [@dittmarSocialPsychologyMaterial1992, @pierceTheoryPsychologicalOwnership2001]. 
In an Australian donor context, we have provided initial support for the idea that psychological ownership experienced towards a blood collection agency both increases with past donation experience and is positively associated with blood donor self-identity [@edwardsPsychologicalOwnershipIdentity2023]. Further, in a series of semi-structured interviews we have shown that Australian blood donors primarily expressed ownership over the blood donation process (role behaviour), not the blood collection agency (organisation). As such, interventions that enhance the amount of psychological ownership donors experience over their donation have the potential to impact donor retention. 
In this study we try to repeat results from Edwards et al., 2023 in Finland by collecting similar questionnaire data from donors of Finnish Red Cross Blood Service (FRCBS) and modeling the questionnaire data with a structural equation model. We include pre-registered R analysis code for direct repetition of Edwards et al., 2023 in Appendix 1.


## Hypotheses
<!-- List specific, concise, and testable hypotheses. Please state if the hypotheses are directional or non-directional. If directional, state the direction. A predicted effect is also appropriate here. If a specific interaction or moderation is important to your research, you can list that as a separate hypothesis.

Example: If taste affects preference, then mean preference indices will be higher with higher concentrations of sugar. -->

1. The blood donors reported psychological ownership over FRCBS is positively associated with self-identity, which, in turn, is positively associated with intentions to donate blood. That is the lower bound of effect estimate of 95% standardized confidence or credible interval of the indirect pathway between past behavior and intention via both psychological ownership and self-identity (ind_eff =  a1* d21 * b2) is higher than zero. 

2. Psychological ownership over FRCBS increases with donation experience. That is the lower bound of effect estimate of 95% standardized confidence or credible interval of direct effect of past donation behavior to psychological ownership (a1) is higher than zero.


# Design Plan
<!-- In this section, you will be asked to describe the overall design of your study. Remember that this research plan is designed to register a single study, so if you have multiple experimental designs, please complete a separate preregistration. -->



## Study type


**Observational Study**. Data is collected from study subjects that are not randomly assigned to a treatment. This includes surveys, natural experiments, and regression discontinuity designs.



## Blinding
<!-- Blinding describes who is aware of the experimental manipulations within a study. Select all that apply. Is there any additional blinding in this study? -->

No blinding is involved in this study.

## Study design
<!-- Describe your study design. Examples include two-group, factorial, randomized block, and repeated measures. Is it a between (unpaired), within-subject (paired), or mixed design? Describe any counterbalancing required. Typical study designs for observation studies include cohort, cross sectional, and case-control studies.

This question has a variety of possible answers. The key is for a researcher to be as detailed as is necessary given the specifics of their design. Be careful to determine if every parameter has been specified in the description of the study design. There may be some overlap between this question and the following questions. That is OK, as long as sufficient detail is given in one of the areas to provide all of the requested information. For example, if the study design describes a complete factorial, 2 X 3 design and the treatments and levels are specified previously, you do not have to repeat that information.

Example: We have a between subjects design with 1 factor (sugar by mass) with 4 levels. -->

Cross sectional survey study modeled with a structural equation model.

## Randomization
<!-- If you are doing a randomized study, how will you randomize, and at what level? Typical randomization techniques include: simple, block, stratified, and adaptive covariate randomization. If randomization is required for the study, the method should be specified here, not simply the source of random numbers.

Example: We will use block randomization, where each participant will be randomly assigned to one of the four equally sized, predetermined blocks. The random number list used to create these four blocks will be created using the web applications available at https://random.org. -->

A set of blood donors will be randomly selected from all blood donors in FRCBS register who have donated at least once during the 730 preceding the day the questionnaire e-mail will be sent in May 2025 .

# Sampling Plan
<!-- In this section we’ll ask you to describe how you plan to collect samples, as well as the number of samples you plan to collect and your rationale for this decision. Please keep in mind that the data described in this section should be the actual data used for analysis, so if you are using a subset of a larger dataset, please describe the subset that will actually be used in your study. -->



## Existing data
<!-- Preregistration is designed to make clear the distinction between confirmatory tests, specified prior to seeing the data, and exploratory analyses conducted after observing the data. Therefore, creating a research plan in which existing data will be used presents unique challenges. Please select the description that best describes your situation. Please do not hesitate to contact us if you have questions about how to answer this question (prereg@cos.io). -->

**Registration prior to creation of data**. As of the date of submission of this research plan for preregistration, the data have not yet been collected, created, or realized. 


## Explanation of existing data
<!-- If you indicate that you will be using some data that already exist in this study, please describe the steps you have taken to assure that you are unaware of any patterns or summary statistics in the data. This may include an explanation of how access to the data has been limited, who has observed the data, or how you have avoided observing any analysis of the specific data you will use in your study.

An appropriate instance of using existing data would be collecting a sample size much larger than is required for the study, using a small portion of it to conduct exploratory analysis, and then registering one particular analysis that showed promising results. After registration, conduct the specified analysis on that part of the dataset that had not been investigated by the researcher up to that point.

Example: An appropriate instance of using existing data would be collecting a sample size much larger than is required for the study, using a small portion of it to conduct exploratory analysis, and then registering one particular analysis that showed promising results. After registration, conduct the specified analysis on that part of the dataset that had not been investigated by the researcher up to that point. -->

No pre-exisiting data is used.

## Data collection procedures
<!-- Please describe the process by which you will collect your data. If you are using human subjects, this should include the population from which you obtain subjects, recruitment efforts, payment for participation, how subjects will be selected for eligibility from the initial pool (e.g. inclusion and exclusion rules), and your study timeline. For studies that donÍt include human subjects, include information about how you will collect samples, duration of data gathering efforts, source or location of samples, or batch numbers you will use.

The answer to this question requires a specific set of instructions so that another person could repeat the data collection procedures and recreate the study population. Alternatively, if the study population would be unable to be reproduced because it relies on a specific set of circumstances unlikely to be recreated (e.g., a community of people from a specific time and location), the criteria and methods for creating the group and the rationale for this unique set of subjects should be clear.

Example: Participants will be recruited through advertisements at local pastry shops. Participants will be paid $10 for agreeing to participate (raised to $30 if our sample size is not reached within 15 days of beginning recruitment). Participants must be at least 18 years old and be able to eat the ingredients of the pastries. -->

An e-mail inviting to fill an online questionnaire will be sent to the randomly selected blood donors. No recompensation will be offered to participants. Participants must be between 18 and 72 years old.


## Sample size
<!-- Describe the sample size of your study. How many units will be analyzed in the study? This could be the number of people, birds, classrooms, plots, interactions, or countries included. If the units are not individuals, then describe the size requirements for each unit. If you are using a clustered or multilevel design, how many units are you collecting at each level of the analysis? For some studies, this will simply be the number of samples or the number of clusters. For others, this could be an expected range, minimum, or maximum number.

Example: Our target sample size is 280 participants. We will attempt to recruit up to 320, assuming that not all will complete the total task. -->

Our target sample size is 1000 participants. Based on previous participation rates an email will be sent to 5000 random donors.


## Sample size rationale
<!-- This could include a power analysis or an arbitrary constraint such as time, money, or personnel. This gives you an opportunity to specifically state how the sample size will be determined. A wide range of possible answers is acceptable; remember that transparency is more important than principled justifications. If you state any reason for a sample size upfront, it is better than stating no reason and leaving the reader to "fill in the blanks." Acceptable rationales include: a power analysis, an arbitrary number of subjects, or a number based on time or monetary constraints.

Example: We used the software program G*Power to conduct a power analysis. Our goal was to obtain .95 power to detect a medium effect size of .25 at the standard .05 alpha error probability. -->

The blood donor participants (n = 255) and the standardised regression coefficients from our previous serial mediation model (Edwards et al., 2023), were imputed into a Monte Carlo Power analysis for indirect effects (Schoemann, Boulton, & Short, 2017) to estimate sample size. For an alpha set at .05, usable data from 369 participants is required to achieve .9 power for our intended serial mediation model. With a target sample of 1000 participants we hope to carry out sex stratified analysis and further exploratory analysis.

## Stopping rule
<!-- If your data collection procedures do not give you full control over your exact sample size, specify how you will decide when to terminate your data collection. 

You may specify a stopping rule based on p-values only in the specific case of sequential analyses with pre-specified checkpoints, alphas levels, and stopping rules. Unacceptable rationales include stopping based on p-values if checkpoints and stopping rules are not specified. If you have control over your sample size, then including a stopping rule is not necessary, though it must be clear in this question or a previous question how an exact sample size is attained.

Example: We will post participant sign-up slots by week on the preceding Friday night, with 20 spots posted per week. We will post 20 new slots each week if, on that Friday night, we are below 320 participants. -->

The online questionnaire will be open for 2 weeks.



# Variables
<!-- In this section you can describe all variables (both manipulated and measured variables) that will later be used in your confirmatory analysis plan. In your analysis plan, you will have the opportunity to describe how each variable will be used. If you have variables which you are measuring for exploratory analyses, you are not required to list them, though you are permitted to do so. -->


## Manipulated variables
<!-- Describe all variables you plan to manipulate and the levels or treatment arms of each variable. This is not applicable to any observational study. For any experimental manipulation, you should give a precise definition of each manipulated variable. This must include a precise description of the levels at which each variable will be set, or a specific definition for each categorical treatment. For example, “loud or quiet,” should instead give either a precise decibel level or a means of recreating each level. 'Presence/absence' or 'positive/negative' is an acceptable description if the variable is precisely described.

Example: We manipulated the percentage of sugar by mass added to brownies. The four levels of this categorical variable are: 15%, 20%, 25%, or 40% cane sugar by mass. -->


## Measured variables
<!-- Describe each variable that you will measure. This will include outcome measures, as well as any predictors or covariates that you will measure. You do not need to include any variables that you plan on collecting if they are not going to be included in the confirmatory analyses of this study.

Observational studies and meta-analyses will include only measured variables. As with the previous questions, the answers here must be precise. For example, 'intelligence,' 'accuracy,' 'aggression,' and 'color' are too vague. Acceptable alternatives could be 'IQ as measured by Wechsler Adult Intelligence Scale' 'percent correct,' 'number of threat displays,' and 'percent reflectance at 400 nm.'

Example: The single outcome variable will be the perceived tastiness of the single brownie each participant will eat. We will measure this by asking participants ‘How much did you enjoy eating the brownie’ (on a scale of 1-7, 1 being 'not at all', 7 being 'a great deal') and 'How good did the brownie taste' (on a scale of 1-7, 1 being 'very bad', 7 being 'very good'). -->

All Likert items are scored 1 (strongly disagree) to 7 (strongly agree).

Items:
<table>

<tr>
<td>Psychological ownership</td>
</tr>
<tr>
<td>po01 1. I feel a very high degree of personal ownership of donating blood. [Likert]</td>
</tr>

<tr> 
<td>po02 2. I feel like donating blood belongs to me. [Likert] </td> 
</tr>

<tr>
<td>po03 3. I feel like I own donating blood. [Likert]</td> 
</tr>

<tr> 
<td>Self-identity</td> 
</tr>

<tr>
<td>si01 1. Donating blood is important to me. [Likert]</td> 
<tr>si02 2. I am like the kind of person who donates blood. [Likert]</td> 
</tr>

<tr> 
<td>si03 3. Donating blood is an important part of who I am. [Likert]</td> 
</tr>

<tr>
<td>Intention</td>
</tr>

<tr>
<td>it01 1. I would like to donate blood in the future. [Likert]</td>   
</tr>

<tr>
<td>it02 2. I intend to donate blood in the future. [Likert]</td>
</tr>

<tr>
<td>it03 3. I intend to make more than just a one-off blood donation. [Likert]</td>
</tr>

<tr>
<td>
Intention to donate for emergency</td>
</tr>

<tr>
<td>ie01 1. I would be willing to donate blood if I received an urgent callout from the Finnish Red Cross Blood Service. [Likert]</td>
</tr>

<tr>
<td>Antecedents of psychological ownership</td>
</tr>

<tr>
<td>Control</td>
</tr>

<tr>
<td>ac01  1. I have influence over the things that affect me while donating blood. [Likert]</td>
</tr>

<tr>
<td>ac02 2. I control the location and scheduling for donating blood. [Likert]</td>
</tr>
<tr>

<td>ac03 3. I influence decisions related to my blood donation. [Likert]</td>
</tr>

<tr>
<td>ac04 4. In general, I have control over donating blood. [Likert]</td>
</tr>
<tr>
<td>Intimate knowledge</td>
</tr>

<tr>
<td>ai01 1. I am intimately familiar with what is going on with regard to donating blood. [Likert]</td>
</tr>

<tr>
<td>ai02 2. I have a depth of knowledge as it relates to donating blood. [Likert]</td>
</tr>

<tr>
<td>ai03 3. I have a comprehensive understanding of donating blood. [Likert]</td>
</tr>

<tr>
<td>ai04 4. I have a broad understanding of donating blood. [Likert]</td>
</tr>

<tr>
<td>Self-Investment</td>
</tr>

<tr>
<td>iv01 1.	I have invested a major part of myself into donating blood. [Likert]</td>
</tr>

<tr>
<td>iv02 2. I have invested a significant amount of my time into donating blood. [Likert] </td>
</tr>

<tr>
<td>iv03 3. Overall, I invested a lot into donating blood. [Likert]</td>
</tr>

<tr>
<td>Blood donation history</td>
</tr>

<tr>
<td>bd01 1. Do you believe that you are currently eligible to donate blood [yes, no, unsure]</td>
</tr>

<tr>
<td>bd02 2. How many times in total have you donated blood at the Finnish Red Cross Blood Service Finland? [select number]</td>
</tr>

<tr>
<td>bd03 3. How many times in the last two years have you donated at the Finnish Red Cross Blood Service? [select number]</td>
</tr>

<tr>
<td>bd04 4. When did you last attend a Finnish Red Cross blood donation centre with the intention of donating blood? [select date]</td>
</tr>

<tr>
<td>Demographics</td>
</tr>

<tr>
<td>de01 1. What is your gender? [man, woman, non-binary, prefer to not disclose, prefer to self-describe (open response)]</td>
</tr>

<tr>
<td>de02 2. How old are you today? [select number]</td>
</tr>
</table>




## Indices
<!-- If any measurements are  going to be combined into an index (or even a mean), what measures will you use and how will they be combined? Include either a formula or a precise description of your method. If your are using a more complicated statistical method to combine measures (e.g. a factor analysis), you can note that here but describe the exact method in the analysis plan section.

If you are using multiple pieces of data to construct a single variable, how will this occur? Both the data that are included and the formula or weights for each measure must be specified. Standard summary statistics, such as "means" do not require a formula, though more complicated indices require either the exact formula or, if it is an established index in the field, the index must be unambiguously defined. For example, "biodiversity index" is too broad, whereas "Shannon’s biodiversity index" is appropriate.

Example: We will take the mean of the two questions above to create a single measure of 'brownie enjoyment.'  -->

For sum score model latent variables will be formed by summing measured items:

Psychological ownership = po01 + po02 + po03

Self-identity           = si01 + si02 + si03

Intention               = it01 + it02 + it03

For structural equation models using latent variables the same variables will be used as constituent items of the latent variable. Instead of using just question bd02 as in the original publication a donation history latent variable will be formed as:

Blood donation history = bd02 + bd03 + bd04



# Analysis Plan
<!-- You may describe one or more confirmatory analysis in this preregistration. Please remember that all analyses specified below must be reported in the final article, and any additional analyses must be noted as exploratory or hypothesis generating.

A confirmatory analysis plan must state up front which variables are predictors (independent) and which are the outcomes (dependent), otherwise it is an exploratory analysis. You are allowed to describe any exploratory work here, but a clear confirmatory analysis is required. -->

Bivariate correlations will be calculated between all primary variables included in the survey (past behaviour, psychological ownership, self-identity, intention). Following this, a serial mediation will be conducted. Previous blood donation behaviour (from the last two years) will be entered as the causal variable, psychological ownership and then identity as the serial mediators, and blood donation intentions as the outcome variable. 


## Statistical models
<!-- What statistical model will you use to test each hypothesis? Please include the type of model (e.g. ANOVA, multiple regression, SEM, etc) and the specification of the model (this includes each variable that will be included as predictors, outcomes, or covariates). Please specify any interactions, subgroup analyses, pairwise or complex contrasts, or follow-up tests from omnibus tests. If you plan on using any positive controls, negative controls, or manipulation checks you may mention that here. Remember that any test not included here must be noted as an exploratory test in your final article.

This is perhaps the most important and most complicated question within the preregistration. As with all of the other questions, the key is to provide a specific recipe for analyzing the collected data. Ask yourself: is enough detail provided to run the same analysis again with the information provided by the user? Be aware for instances where the statistical models appear specific, but actually leave openings for the precise test. See the following examples:

- If someone specifies a 2x3 ANOVA with both factors within subjects, there is still flexibility with the various types of ANOVAs that could be run. Either a repeated measures ANOVA (RMANOVA) or a multivariate ANOVA (MANOVA) could be used for that design, which are two different tests. 
- If you are going to perform a sequential analysis and check after 50, 100, and 150 samples, you must also specify the p-values you’ll test against at those three points.

Example:  We will use a one-way between subjects ANOVA to analyze our results. The manipulated, categorical independent variable is 'sugar' whereas the dependent variable is our taste index. -->


We will model the data with a structural equation model. The exact model, R code to run it and example analysis with simulated data can be found in Appendix 1. 


## Transformations
<!-- If you plan on transforming, centering, recoding the data, or will require a coding scheme for categorical variables, please describe that process. If any categorical predictors are included in a regression, indicate how those variables will be coded (e.g. dummy coding, summation coding, etc.) and what the reference category will be.

Example: The "Effect of sugar on brownie tastiness" does not require any additional transformations. However, if it were using a regression analysis and each level of sweet had been categorically described (e.g. not sweet, somewhat sweet, sweet, and very sweet), 'sweet' could be dummy coded with 'not sweet' as the reference category. -->

Number of life time donations (bd02) and number of donations in last years (bd03) and likert scale measured variables (po01-3, si01-03, it01-03, ac01-04, iv01-03) will be treated as numeric. Last donation date (bd04) will transformed to days from last donation by subtracting date of questionnaire response from date of last donation.



## Inference criteria
<!-- What criteria will you use to make inferences? Please describe the information youÍll use (e.g. p-values, bayes factors, specific model fit indices), as well as cut-off criterion, where appropriate. Will you be using one or two tailed tests for each of your analyses? If you are comparing multiple conditions or testing multiple hypotheses, will you account for this?

p-values, confidence intervals, and effect sizes are standard means for making an inference, and any level is acceptable, though some criteria must be specified in this or previous fields. Bayesian analyses should specify a Bayes factor or a credible interval. If you are selecting models, then how will you determine the relative quality of each? In regards to multiple comparisons, this is a question with few "wrong" answers. In other words, transparency is more important than any specific method of controlling the false discovery rate or false error rate. One may state an intention to report all tests conducted or one may conduct a specific correction procedure; either strategy is acceptable.

Example: We will use the standard p<.05 criteria for determining if the ANOVA and the post hoc test suggest that the results are significantly different from those expected if the null hypothesis were correct. The post-hoc Tukey-Kramer test adjusts for multiple comparisons. -->

We will model the hypothesis through alternative models:

a) Sum score model with robust estimator and listwise deletion

b) Sum score model with bootstrapping and listwise deletion

c) Sum score model with robust estimator and fiml

d) Sum score model with bootstrapping and fiml

e) Latent factor model with robust estimator and listwise deletion

f) Latent factor model with boostrapping and listwise deletion

g) Latent factor model with robust estimator and fiml

h) Latent factor model with bootstrapping and fiml

Comparative results from these models will presented and their merits discussed.
95 % confidence or credible intervals will be used to decide if an effect is considered significant or not.

Further details of the models can be found in Appendix 1.



## Data exclusion
<!-- How will you determine what data or samples, if any, to exclude from your analyses? How will outliers be handled? Will you use any awareness check? Any rule for excluding a particular set of data is acceptable. One may describe rules for excluding a participant or for identifying outlier data.

Example: No checks will be performed to determine eligibility for inclusion besides verification that each subject answered each of the three tastiness indices. Outliers will be included in the analysis. -->

All donors answering to question de01 other than "man" or "women" will be excluded as donation policies depend on sex. All donors answering to question bd01 "no" will be excluded as we are interested in persons eligible to donate.


## Missing data
<!-- How will you deal with incomplete or missing data? Any relevant explanation is acceptable. As a final reminder, remember that the final analysis must follow the specified plan, and deviations must be either strongly justified or included as a separate, exploratory analysis.

Example: If a subject does not complete any of the three indices of tastiness, that subject will not be included in the analysis. -->

Missing data will be analysed for possible biases and Little’s MCAR test carried out to assess randomness of missing data. Models using "full information maximum likelihood" approach or listwise deletion will be fitted to inspect the effect of these modelling choices (see Appendix 1 for details). All these results will be reported and discussed, acknowledging that there is no well-accepted method of dealing with data that is not missing at random

## Exploratory analyses (optional)
<!-- If you plan to explore your data set to look for unexpected differences or relationships, you may describe those tests here. An exploratory test is any test where a prediction is not made up front, or there are multiple possible tests that you are going to use. A statistically significant finding in an exploratory test is a great way to form a new confirmatory hypothesis, which could be registered at a later time.

Example: We expect that certain demographic traits may be related to taste preferences. Therefore, we will look for relationships between demographic variables (age, gender, income, and marital status) and the primary outcome measures of taste preferences. -->

Qualitative content analysis will be conducted on participants answers to the open-response question (What do you remember about the first time you donated blood?). Bivariate correlations will be calculated to compare donors’ willingness to respond to a call-out to past blood donation behaviour, psychological ownership, self-identity, and intention to donate blood.
If there is sufficient data we will stratify models by sex.
Model improvements will be considered if deemed appropriate.


# Other

## Other 
<!-- If there is any additional information that you feel needs to be included in your preregistration, please enter it here. Literature cited, disclosures of any related work such as replications or work that uses the same data, or other context that will be helpful for future readers would be appropriate here. -->


\includepdf[pages={-}]{preregistration_code.pdf}

# References


::: {#refs custom-style="Bibliography"}
:::

 
\vspace{-2pc}
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{-1in}
\setlength{\parskip}{8pt}
\noindent
